# Generated by Django 3.2.4 on 2021-06-02 23:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tasks', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='task',
            name='status',
            field=models.BooleanField(blank=True, choices=[(0, 'On going'), (1, 'Done')], null=True),
        ),
    ]
