# Generated by Django 3.2.4 on 2021-06-03 00:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tasks', '0002_alter_task_status'),
    ]

    operations = [
        migrations.AlterField(
            model_name='task',
            name='status',
            field=models.BooleanField(choices=[(0, 'On going'), (1, 'Done')], null=True),
        ),
        migrations.AlterField(
            model_name='user',
            name='status',
            field=models.BooleanField(choices=[(0, 'Free'), (1, 'Busy')], default=1),
        ),
    ]
