# Generated by Django 3.2.4 on 2021-06-04 19:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tasks', '0003_auto_20210604_0639'),
    ]

    operations = [
        migrations.AlterField(
            model_name='task',
            name='assign_status',
            field=models.BooleanField(choices=[(0, 'Unasigned'), (1, 'Assigned')], default=1, null=True),
        ),
        migrations.AlterField(
            model_name='user',
            name='department',
            field=models.CharField(choices=[('HR', 'Human Resources')], max_length=50),
        ),
        migrations.AlterField(
            model_name='user',
            name='designation',
            field=models.CharField(choices=[('General Member', 'General Member'), ('Executive', 'Executive'), ('Senior Executive', 'Senior Executive'), ('Assistant Director', 'Assistant Director'), ('Director', 'Director')], max_length=20),
        ),
    ]
