# Generated by Django 3.2.4 on 2021-07-26 12:25

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tasks', '0003_auto_20210724_1825'),
    ]

    operations = [
        migrations.CreateModel(
            name='Announcements',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=200)),
                ('about', models.TextField(blank=True, null=True)),
                ('instructions', models.TextField(blank=True, null=True)),
                ('url', models.URLField(blank=True, null=True)),
                ('tagged', models.BooleanField(blank=True, choices=[(0, 'None'), (1, 'Everyone')], default=0, null=True)),
                ('event_date', models.DateField(blank=True, default=datetime.datetime.now)),
            ],
        ),
    ]
