# Generated by Django 3.2.4 on 2021-06-04 19:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tasks', '0004_auto_20210605_0114'),
    ]

    operations = [
        migrations.AlterField(
            model_name='task',
            name='assign_status',
            field=models.BooleanField(choices=[(1, 'Asigned'), (0, 'Unassigned')], default=1, null=True),
        ),
    ]
