# Generated by Django 3.2.4 on 2021-07-26 12:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tasks', '0004_announcements'),
    ]

    operations = [
        migrations.AddField(
            model_name='announcements',
            name='picture',
            field=models.ImageField(blank=True, null=True, upload_to=''),
        ),
    ]
