# Generated by Django 3.2.4 on 2021-07-26 12:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tasks', '0005_announcements_picture'),
    ]

    operations = [
        migrations.AddField(
            model_name='announcements',
            name='duration',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
    ]
