# Generated by Django 3.2.4 on 2021-06-04 19:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tasks', '0005_alter_task_assign_status'),
    ]

    operations = [
        migrations.AlterField(
            model_name='task',
            name='assign_status',
            field=models.BooleanField(choices=[(0, 'Asigned'), (1, 'Unassigned')], default=1, null=True),
        ),
    ]
