# Generated by Django 3.2.4 on 2021-07-26 12:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tasks', '0006_announcements_duration'),
    ]

    operations = [
        migrations.AlterField(
            model_name='announcements',
            name='about',
            field=models.TextField(blank=True, max_length=1000, null=True),
        ),
        migrations.AlterField(
            model_name='announcements',
            name='instructions',
            field=models.TextField(blank=True, max_length=1000, null=True),
        ),
    ]
