# Generated by Django 3.2.4 on 2021-06-05 12:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tasks', '0006_alter_task_assign_status'),
    ]

    operations = [
        migrations.AlterField(
            model_name='task',
            name='assign_status',
            field=models.BooleanField(choices=[(0, 'Unasigned'), (1, 'Assigned')], default=0, null=True),
        ),
    ]
