# Generated by Django 3.2.4 on 2021-07-26 14:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tasks', '0007_auto_20210726_1846'),
    ]

    operations = [
        migrations.AddField(
            model_name='announcements',
            name='platform',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
    ]
