# Generated by Django 3.2.4 on 2021-06-06 06:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tasks', '0008_alter_user_date_joined'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='status',
            field=models.BooleanField(choices=[(0, 'Free'), (1, 'Busy')], default=1, null=True),
        ),
    ]
