# Generated by Django 3.2.4 on 2021-07-26 15:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tasks', '0008_announcements_platform'),
    ]

    operations = [
        migrations.AlterField(
            model_name='announcements',
            name='url',
            field=models.CharField(blank=True, max_length=200, null=True),
        ),
    ]
