# Generated by Django 3.2.4 on 2021-07-26 15:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tasks', '0009_alter_announcements_url'),
    ]

    operations = [
        migrations.AlterField(
            model_name='announcements',
            name='url',
            field=models.URLField(blank=True, null=True),
        ),
    ]
