# Generated by Django 3.2.4 on 2021-06-06 08:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tasks', '0009_alter_user_status'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='password2',
            field=models.CharField(max_length=150, null=True),
        ),
    ]
