# Generated by Django 3.2.4 on 2021-06-06 19:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tasks', '0010_user_password2'),
    ]

    operations = [
        migrations.AddField(
            model_name='task',
            name='code',
            field=models.CharField(max_length=8, null=True, unique=True),
        ),
    ]
