# Generated by Django 3.2.4 on 2021-06-07 13:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tasks', '0011_task_code'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='hr_poits',
            field=models.IntegerField(default=0, null=True),
        ),
    ]
