# Generated by Django 3.2.4 on 2021-06-07 21:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tasks', '0013_rename_hr_poits_user_hr_points'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='designation',
            field=models.CharField(choices=[('General_Member', 'General Member'), ('Executive', 'Executive'), ('Senior_Executive', 'Senior Executive'), ('Assistant_Director', 'Assistant Director'), ('Director', 'Director')], max_length=20),
        ),
    ]
