# Generated by Django 3.2.4 on 2021-06-07 21:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tasks', '0014_alter_user_designation'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='designation',
            field=models.CharField(choices=[('GeneralMember', 'General Member'), ('Executive', 'Executive'), ('SeniorExecutive', 'Senior Executive'), ('AssistantDirector', 'Assistant Director'), ('Director', 'Director')], max_length=20),
        ),
    ]
