# Generated by Django 3.2.4 on 2021-06-07 21:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tasks', '0015_alter_user_designation'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='designation',
            field=models.CharField(choices=[('General Member', 'General Member'), ('Executive', 'Executive'), ('Senior Executive', 'Senior Executive'), ('Assistant Director', 'Assistant Director'), ('Director', 'Director')], max_length=20),
        ),
    ]
