# Generated by Django 3.2.4 on 2021-06-09 04:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tasks', '0016_alter_user_designation'),
    ]

    operations = [
        migrations.CreateModel(
            name='InviteMember',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('email', models.EmailField(max_length=100)),
                ('username', models.CharField(max_length=100)),
            ],
        ),
    ]
