# Generated by Django 3.2.4 on 2021-06-09 04:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tasks', '0017_invitemember'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='in_club_name',
            field=models.CharField(blank=True, max_length=70),
        ),
    ]
