# Generated by Django 3.2.4 on 2021-06-09 05:21

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('tasks', '0019_auto_20210609_1041'),
    ]

    operations = [
        migrations.DeleteModel(
            name='InviteMember',
        ),
    ]
