# Generated by Django 3.2.4 on 2021-06-10 04:22

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('tasks', '0020_delete_invitemember'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='user',
            name='password2',
        ),
    ]
